<?php

class Column
{
	const COMPOUND_ID = "COMPOUND_ID";
	const COMPOUND_TITLE = "TITLE";
	const COMPOUND_FORMULA = "FORMULA";
	const COMPOUND_EXACT_MASS = "EXACT_MASS";
	const COMPOUND_ION_MODE = "ION_MODE";
	
	const COMPOUND_NAME_ID = "CH_NAME_ID";
	const COMPOUND_NAME_NAME = "CH_NAME";
	
	const INSTRUMENT_ID = "INSTRUMENT_ID";
	const INSTRUMENT_TYPE = "INSTRUMENT_TYPE";
	
	const MS_ID = "MS_ID";
	const MS_TYPE = "MS_TYPE";
	
	const PEAK_ID = "PEAK_ID";
	const PEAK_MZ = "MZ";
	const PEAK_INTENSITY = "INTENSITY";
	const PEAK_RELATIVE_INTENSITY = "RELATIVE_INTENSITY";
}

?>