<?php

class Column
{
	const COMPOUND_ID = "COMPOUND_ID";
	const COMPOUND_TITLE = "TITLE";
	const COMPOUND_AUTHORS = "AUTHORS";
	const COMPOUND_INSTRUMENT = "INSTRUMENT";
	const COMPOUND_LICENSE = "LICENSE";
	const COMPOUND_FORMULA = "FORMULA";
	const PUBCHEM_ID = "PUBCHEM_ID";
	const PUBCHEM_ID_TYPE = "PUBCHEM_ID_TYPE";
	const COMPOUND_EXACT_MASS = "EXACT_MASS";
	const COMPOUND_ION_MODE = "ION_MODE";
	
	const COMPOUND_NAME_ID = "COMPOUND_NAME_ID";
	const COMPOUND_NAME_NAME = "NAME";
	
	const INSTRUMENT_ID = "INSTRUMENT_ID";
	const INSTRUMENT_TYPE = "INSTRUMENT_TYPE";
	
	const MS_TYPE_ID = "MS_TYPE_ID";
	const MS_TYPE_NAME = "MS_TYPE_NAME";
	
	const SYNC_ID = "SYNC_ID";
	const SYNC_REPOSITORY = "REPOSITORY";
	const SYNC_RESOURCE = "RESOURCE";
	const SYNC_MEDIA_TYPE = "MEDIA_TYPE";
	const SYNC_UPDATED = "UPDATED";
	const SYNC_TIMESTAMP = "TIMESTAMP";
	
	const PEAK_ID = "PEAK_ID";
	const PEAK_MZ = "MZ";
	const PEAK_INTENSITY = "INTENSITY";
	const PEAK_RELATIVE_INTENSITY = "RELATIVE_INTENSITY";
}

?>